[pytest]

addopts = -vs --alluredir=temps --clean-alluredir

# 日志配置
# 日志文件位置
log_file = ./logs/frame.log
# 日志的级别,DEBUG调试，INFO信息，WARNING警告，ERROR错误，CRITICAL致命错误
log_file_level = INFO
# 日志格式
log_file_format = %(asctime)s - %(filename)s - %(levelname)s - %(message)s

[base_url]
test_base_url: http://localhost:8888
dev_base_url: http://localhost:8888