name: "Test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    container: astral/uv:python3.12-bookworm-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install
        run: uv sync
      - name: Test
        run: uv run run.py test_fastapi
